### PR TITLE
Vaadin 7 migration

### PR DESCRIPTION
**Pull request by amahdy**
WIP - Initial UI migration

### CODE REVIEW

**Comment by amahdy** [comment]
Ready for review / merge.

**Comment by eschabell** [comment]
I got a successful install build but noticed this in the output:

Error parsing jar file: file:/Users/erics/demo-projects/brms/brms-coolstore-demo/projects/brms-coolstore-demo/target/classes
Widgetsets found from classpath:
	com.vaadin.DefaultWidgetSet in file:/Users/erics/demo-projects/maven-repository/com/vaadin/vaadin-client/7.5.10/vaadin-client-7.5.10.jar

Search took 22ms
0 addons widget set found.


Was this an error or ok?

**Comment by eschabell** [comment]
The rest works like a charm, looks really sharp and like that you put a screen behind the checkout. Merging to master and will promote this online.

**Comment by amahdy** [comment]
@eschabell please try:

`mvn clean vaadin:clean vaadin:compile`

**Comment by eschabell** [comment]
Will get to this next week, lost my laptop SSD drive, off for repairs until then.

**Pull request merged**
